### ISSUE TITLE
Crash when there's more than 8 touches

### ISSUE THREAD

**Issue by BUGO07** [rust-mobile/android-activity#175]
12-13 13:28:11.510 32446 32479 I RustStdoutStderr: thread '<unnamed>' panicked at /home/bugo07/.cargo/registry/src/index.crates.io-6f17d22bba15001f/android-activity-0.6.0/src/game_activity/input.rs:136:13:
12-13 13:28:11.510 32446 32479 I RustStdoutStderr: Pointer index 8 is out of bounds
12-13 13:28:11.510 32446 32479 I RustStdoutStderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by rib** [comment]
> My guess currently is that maybe the older version of `GameActivity` also only has a buffer for 8 pointers but maybe it doesn't correctly clamp the value reported in `::pointer_count()`.

Yeah, it's exactly this: https://github.com/rust-mobile/android-activity/blob/0d299300f4120821ae1fcaaf0276129c512c2c96/android-activity/game-activity-csrc/game-activity/GameActivityEvents.cpp#L200-L201

The GameActivity 2.x backend was blindly forwarding the `pointerCount` from Java but it was only copying a maximum of 8 pointers worth of data.

So this is fixed in `main` with the update to `GameActivity` 4.0.0

For reference, I'm looking to do a 0.6.1 release relatively soon hopefully (sorry that doesn't count for much in the context of a bug filed in 2024)

**Comment by rib** [comment]
Since releasing android-activity 0.6.1, which updates to GameActivity 4.4.0 this issue should be fixed now (with the caveat that the GameActivity implementation has a hard limit of 8 concurrent touch points): https://github.com/rust-mobile/android-activity/releases/tag/v0.6.1

Please re-open if you continue to see an issue here after updating

**Comment by Johannes0021** [comment]
I still have this issue with android-activity from main. I'm using bevy and:
```toml
[patch.crates-io]
android-activity = { git = "https://github.com/rust-mobile/android-activity", branch = "main" }
```

**Comment by Johannes0021** [comment]
Workaround, not sure if this has any bad side effects: https://github.com/Johannes0021/android-activity/commit/d31a501a252a2dbb359bd7b4673128017aab7746
